// Generated by npm run images:webp. Filenames contain a content hash for immutable caching.
export const workImageSources: Record<string, { src: string; srcSet: string; width: number; height: number }> = {
  "/assistant-min.webp": {
    "width": 2400,
    "height": 1620,
    "src": "/work-images/assistant-min-1200-c2fcf5f100f3.webp",
    "srcSet": "/work-images/assistant-min-640-9d6c291d990e.webp 640w, /work-images/assistant-min-1200-c2fcf5f100f3.webp 1200w, /work-images/assistant-min-1920-9d7f4169544c.webp 1920w, /work-images/assistant-min-2400-d39b77eccb01.webp 2400w"
  },
  "/bookshelf-ai-min.webp": {
    "width": 2400,
    "height": 1620,
    "src": "/work-images/bookshelf-ai-min-1200-e59386918e23.webp",
    "srcSet": "/work-images/bookshelf-ai-min-640-8ad0b6068fa5.webp 640w, /work-images/bookshelf-ai-min-1200-e59386918e23.webp 1200w, /work-images/bookshelf-ai-min-1920-72f21342db66.webp 1920w, /work-images/bookshelf-ai-min-2400-3997e76189fd.webp 2400w"
  },
  "/mobile-min.webp": {
    "width": 2400,
    "height": 1620,
    "src": "/work-images/mobile-min-1200-b8f3794843eb.webp",
    "srcSet": "/work-images/mobile-min-640-e9aed7af93a8.webp 640w, /work-images/mobile-min-1200-b8f3794843eb.webp 1200w, /work-images/mobile-min-1920-24f9305d0b9b.webp 1920w, /work-images/mobile-min-2400-85befaffc9b4.webp 2400w"
  },
  "/task-master-min.webp": {
    "width": 2400,
    "height": 1620,
    "src": "/work-images/task-master-min-1200-a452fcf1722f.webp",
    "srcSet": "/work-images/task-master-min-640-942e01f28ba5.webp 640w, /work-images/task-master-min-1200-a452fcf1722f.webp 1200w, /work-images/task-master-min-1920-3038aef42730.webp 1920w, /work-images/task-master-min-2400-83a6983a0747.webp 2400w"
  },
  "/taxi-app-min.webp": {
    "width": 2400,
    "height": 1620,
    "src": "/work-images/taxi-app-min-1200-70cc5e128198.webp",
    "srcSet": "/work-images/taxi-app-min-640-4b4742ee2640.webp 640w, /work-images/taxi-app-min-1200-70cc5e128198.webp 1200w, /work-images/taxi-app-min-1920-38be66a4575e.webp 1920w, /work-images/taxi-app-min-2400-643a6397d981.webp 2400w"
  },
  "/video-ai-min.webp": {
    "width": 2400,
    "height": 1620,
    "src": "/work-images/video-ai-min-1200-8e2009e6f999.webp",
    "srcSet": "/work-images/video-ai-min-640-22949c1558ae.webp 640w, /work-images/video-ai-min-1200-8e2009e6f999.webp 1200w, /work-images/video-ai-min-1920-5ccb3d01bb48.webp 1920w, /work-images/video-ai-min-2400-c169bc6d9a42.webp 2400w"
  },
  "/web-pages-min.webp": {
    "width": 2400,
    "height": 1620,
    "src": "/work-images/web-pages-min-1200-7f924a042ba6.webp",
    "srcSet": "/work-images/web-pages-min-640-f4824aaaed51.webp 640w, /work-images/web-pages-min-1200-7f924a042ba6.webp 1200w, /work-images/web-pages-min-1920-931092b64c67.webp 1920w, /work-images/web-pages-min-2400-fd862b734ff3.webp 2400w"
  },
  "/case-studies/luminar-collage/section-1.webp": {
    "width": 1600,
    "height": 1200,
    "src": "/work-images/case-studies-luminar-collage-section-1-1200-7c5d43321e57.webp",
    "srcSet": "/work-images/case-studies-luminar-collage-section-1-640-a936d3ba3f1a.webp 640w, /work-images/case-studies-luminar-collage-section-1-1200-7c5d43321e57.webp 1200w, /work-images/case-studies-luminar-collage-section-1-1600-fb39f10a0bed.webp 1600w"
  },
  "/case-studies/luminar-collage/section-2.webp": {
    "width": 1600,
    "height": 1200,
    "src": "/work-images/case-studies-luminar-collage-section-2-1200-ccc8e953985d.webp",
    "srcSet": "/work-images/case-studies-luminar-collage-section-2-640-7190ac4085c0.webp 640w, /work-images/case-studies-luminar-collage-section-2-1200-ccc8e953985d.webp 1200w, /work-images/case-studies-luminar-collage-section-2-1600-049a75f69602.webp 1600w"
  },
  "/case-studies/luminar-collage/section-3.webp": {
    "width": 1600,
    "height": 1200,
    "src": "/work-images/case-studies-luminar-collage-section-3-1200-64d86111c6fb.webp",
    "srcSet": "/work-images/case-studies-luminar-collage-section-3-640-af467bee817d.webp 640w, /work-images/case-studies-luminar-collage-section-3-1200-64d86111c6fb.webp 1200w, /work-images/case-studies-luminar-collage-section-3-1600-23ebb16a042f.webp 1600w"
  },
  "/case-studies/luminar-collage/section-4.webp": {
    "width": 1600,
    "height": 1200,
    "src": "/work-images/case-studies-luminar-collage-section-4-1200-91c1aacbb824.webp",
    "srcSet": "/work-images/case-studies-luminar-collage-section-4-640-a246354c162b.webp 640w, /work-images/case-studies-luminar-collage-section-4-1200-91c1aacbb824.webp 1200w, /work-images/case-studies-luminar-collage-section-4-1600-da4c9792c73b.webp 1600w"
  },
  "/case-studies/luminar-collage/section-5.webp": {
    "width": 1600,
    "height": 1200,
    "src": "/work-images/case-studies-luminar-collage-section-5-1200-82f2016771f1.webp",
    "srcSet": "/work-images/case-studies-luminar-collage-section-5-640-f9868bf42510.webp 640w, /work-images/case-studies-luminar-collage-section-5-1200-82f2016771f1.webp 1200w, /work-images/case-studies-luminar-collage-section-5-1600-6f648e05e958.webp 1600w"
  }
};
